### ISSUE TITLE
Use `globalThis` when available rather than using `Array` as a namespace

### ISSUE THREAD

**Issue by erights** [benjamn/wryware#347]
Current behavior incompatible with Hardened JS. If run after `lockdown` it will fail to add a static property to the `Array` constructor. If run before `lockdown`, then `lockdown` will try to remove it because it is not on the Hardened JS whitelist (and should not be). If `lockdown` fails to remove it, then `lockdown` fails to create a Hardened JS system.

See https://github.com/endojs/endo/issues/576#issuecomment-1178355710

**Comment by benjamn** [comment]
The changes from #359 (hopefully resolving this issue) are now available in version 0.7.0 of the `@wry/context` package. Thanks for opening this issue @erights!
