### ISSUE TITLE
error TS2694:

### ISSUE THREAD

**Issue by kelvinmbwilo** [benjamn/wryware#4]
node_modules/@wry/context/lib/context.d.ts(6,84): error TS2694: Namespace 'NodeJS' has no exported member 'Timeout'.

**Comment by benjamn** [comment]
Try installing/updating your `@node/types`?

**Comment by adrianenjine** [comment]
For others who have this issue:

I had the same issue.
 - I upgraded node to v10.15.3 from v8
For some reason a brand new app would want to keep the @types/node@8.10.48, so I
 - npm i @types/node@^10
 - ng serve compiles without error

**npm i @types/node@^10**
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @types/node@10.14.7
updated 1 package and audited 42690 packages in 5.189s

**Comment by kamilkisiela** [comment]
@benjamn It's not that easy in some cases. For example, Angular CLI has its own definitions of NodeJS so installing `@types/node` won't work there.

I did some investigation and it seems like we don't need to use `@types/node` at all in `@wry/context`. Only `tests.ts` uses `require` (@types/node thing).

**Comment by mdlavin** [comment]
A temporary workaround I used is to add the following postinstall hook in `package.json`:

```
{
  "scripts" {
     "postinstall": "sed -i'.bak' -e 's/NodeJS.Timeout/NodeJS.Timer/' node_modules/@wry/context/lib/context.d.ts"
  }
}
```
