### ISSUE TITLE
[equality] Compiler option `" target ":" esnext "` in tsconfig.json breaks IE11 support

### ISSUE THREAD

**Issue by saneksa** [benjamn/wryware#99]
![image](https://user-images.githubusercontent.com/33054924/109479875-eb339080-7a8b-11eb-9ca8-a096a411b5da.png)

**Comment by ejosafat** [comment]
It seems that version 0.3.4 breaks IE support, as soon as I updated the package from 0.3.3 to 0.3.4 IE11 breaks with the message unexpected identifier, usually caused for some feature (like `) used in files not transpiled. Also using target: esnext in my tsconfig

**Comment by saneksa** [comment]
https://github.com/benjamn/wryware/blob/e7396f8b2b3d0b5c44b696188d74338188b579ae/packages/equality/tsconfig.json#L4

**Comment by benjamn** [comment]
@saneksa @ejosafat My solution in #102 should be available now in `@wry/equality@0.3.4` (just published to npm). Thanks for noticing/reporting this issue!
